### ISSUE TITLE
Suggestion - Multiple DeathCost

### ISSUE THREAD

**Issue by BroCrows** [HeavenPE/DeathCostBE#1]
Could you make it where you can add multiple DeathCost. 
Ex Config:
Minimum-cost: '100'
Maximum-cost: '1000'

**Comment by HeavenPE** [comment]
i have implemented percentage in the new build. Try it cuz the old builds had a slight confif mistake so it wont work 😁 percentage-deathcost = percent-setin-config × player-current-balance ÷ 100

**Comment by BroCrows** [comment]
Ok thanks!
